# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# HTML Title
title: "Buzzy Bee - TheCrafters001"

# Avatar image path
avatar: "./images/pfp.gif"

# Name section text
name: "TheCrafters001"

# Tagline section text
tagline: >-
    Just a big, fluffy bee!

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-rss"
      text: "Website"
      url: "https://thecrafters001.com/"
      alt: "My Website"
      title: "My Website"
      target: "_blank"
  - link:
      icon: "fa-brands fa-mastodon"
      text: "Meow"
      url: "https://meow.social/@TheCrafters001"
      alt: "Meow (Mastodon)"
      title: "Meow (Mastodon)"
      target: "_blank"
  - link:
      icon: "fa-brands fa-mastodon"
      text: "Donphan"
      url: "https://donphan.social/@TheCrafters001"
      alt: "Donphan (Mastodon)"
      title: "Donphan (Mastodon)"
      target: "_blank"
  - link:
      icon: "fa-brands fa-mastodon"
      text: "Transfur"
      url: "https://transfur.social/@TheCrafters001"
      alt: "Transfur (Mastodon)"
      title: "Transfur (Mastodon)"
      target: "_blank"
  

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/TheCrafters001"
      title: "TheCrafters001's GitHub"
      alt: "TheCrafters001's GitHub"
      target: "_blank"

# Footer text
footer: >
    Heya! I am still working on this page, so please be, ignore any errors or stuff that has yet to be changed.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://thecrafters001.com" target="_blank">TheCrafters001</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>. Profile Picture by <a href="https://toyhou.se/CryptidsCrypt">Crypt</a>.
